services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: loanwizard
      POSTGRES_PASSWORD: localdev
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,sqs
      DEFAULT_REGION: ap-south-1
      DEBUG: 0