import React, { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion, useInView, animate } from 'framer-motion';
import { Video, Shield, Brain, FileCheck, BarChart3, Lock } from 'lucide-react';
import './ProjectOverview.css';

const stats = [
  {
    target: 13,
    unit: 'days',
    label: 'Build timeline',
    caption: 'Hackathon sprint'
  },
  {
    target: 9,
    unit: '',
    label: 'Fraud signals',
    caption: 'Real-time per session'
  },
  {
    target: 0.7497,
    unit: '',
    label: 'Model AUC',
    caption: 'XGBoost on 307K rows',
    format: (value) => value.toFixed(4)
  },
  {
    target: 15,
    unit: 'min',
    label: 'Onboarding time',
    caption: 'vs 3-7 days traditional'
  }
];

const features = [
  {
    icon: Video,
    title: 'Live Video Onboarding',
    description:
      'WebRTC camera session with geo capture, liveness detection, and chunked audio recording for real-time STT processing.',
    link: '#features'
  },
  {
    icon: Shield,
    title: '9-Signal Fraud Engine',
    description:
      'Geo mismatch, VPN detection, age inconsistency, doc vs speech validation, income anomaly, and liveness check — scored 0–100.',
    link: '#features'
  },
  {
    icon: Brain,
    title: 'AI Decision Engine',
    description:
      'XGBoost risk scoring on Home Credit dataset combined with Groq LLM classification produces a 3×4 decision matrix automatically.',
    link: '#features'
  },
  {
    icon: FileCheck,
    title: 'Human-in-the-Loop Review',
    description:
      'Customer validates every auto-filled field before scoring begins. Edit delta tracked — large income corrections raise fraud flags automatically.',
    link: '#features'
  },
  {
    icon: BarChart3,
    title: '3-Variant Loan Offers',
    description:
      'Conservative, standard, and aggressive offers generated by LLM with EMI calculation, tenure options, and plain-English narration.',
    link: '#features'
  },
  {
    icon: Lock,
    title: 'Immutable Audit Trail',
    description:
      'Every session event timestamped and written to DynamoDB. RBI V-CIP compliant. DPDP Act 2023 consent capture. Exportable for audit.',
    link: '#features'
  }
];

const techStack = [
  { label: 'Frontend', value: 'React + Vite' },
  { label: 'Video', value: 'WebRTC getUserMedia' },
  { label: 'Backend', value: 'FastAPI + Python' },
  { label: 'ML', value: 'XGBoost + Groq llama-3.3-70b' },
  { label: 'Storage', value: 'DynamoDB + S3 + PostgreSQL' },
  { label: 'Orchestration', value: 'AWS SQS + Step Functions' },
  { label: 'CV', value: 'DeepFace (age + liveness)' },
  { label: 'OCR', value: 'AWS Textract' }
];

const teamMembers = [
  {
    initials: 'RK',
    name: 'Riyansh Kumar',
    role: 'Video Pipeline',
    detail: 'WebRTC, STT Lambda, CV Lambda, OCR Lambda, HITL review screen'
  },
  {
    initials: 'AR',
    name: 'Alok Raj',
    role: 'Backend & Intelligence',
    detail: 'FastAPI, XGBoost, Groq LLM, fraud engine, decision engine, DynamoDB'
  },
  {
    initials: 'PG',
    name: 'Pranay Gupta',
    role: 'Product & Delivery',
    detail: 'Architecture design, pitch deck, demo script, judging criteria mapping'
  }
];

const judgingCriteria = [
  {
    title: 'End-to-End Digitisation',
    description:
      'Fully paperless video-first journey from secure link to digital consent. Zero manual intervention. Under 15 minutes.'
  },
  {
    title: 'Accuracy & Compliance',
    description:
      'RBI V-CIP consent and geo-tagging. DPDP Act 2023 data minimisation. Digital Lending Directions 2025. Immutable audit trail.'
  },
  {
    title: 'Risk Mitigation',
    description:
      '9-signal fraud engine with cumulative scoring. Liveness detection prevents photo spoofing. Doc vs speech cross-validation blocks high-risk sessions.'
  },
  {
    title: 'Intelligence & Personalization',
    description:
      'Groq LLM classifies intent and persona. XGBoost scores credit risk on 307,511 real loan applications. Explainability layer shows confidence and key factors.'
  },
  {
    title: 'Scalability & Reliability',
    description:
      'SQS async fan-out runs STT, CV, and OCR in parallel. Step Functions orchestrates the state machine. DynamoDB delivers single-digit millisecond reads.'
  }
];

const repoStructure = `
loan-wizard/
├── frontend/
│   ├── src/
│   │   ├── pages/
│   │   │   ├── VideoCall.jsx
│   │   │   ├── Review.jsx
│   │   │   ├── Offer.jsx
│   │   │   ├── Consent.jsx
│   │   │   ├── Success.jsx
│   │   │   ├── Dashboard.jsx
│   │   │   └── SessionDetail.jsx
│   │   ├── components/
│   │   ├── api/
│   │   └── styles/
│   ├── package.json
│   └── vite.config.js
└── backend/
    ├── app/
    ├── infra/
    └── ml/
`;

const FadeInSection = ({ children, className = '', delay = 0, ...props }) => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-120px 0px' });

  return (
    <motion.section
      ref={ref}
      className={className}
      initial={{ opacity: 0, y: 24 }}
      animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 24 }}
      transition={{ duration: 0.6, delay }}
      {...props}
    >
      {children}
    </motion.section>
  );
};

const AnimatedCounter = ({ target, formatValue }) => {
  const ref = useRef(null);
  const [display, setDisplay] = useState(() => (formatValue ? formatValue(0) : '0'));
  const inView = useInView(ref, { once: true, margin: '-80px 0px' });

  useEffect(() => {
    if (!inView) return undefined;
    const animation = animate(0, target, {
      duration: 1.4,
      onUpdate(value) {
        setDisplay(formatValue ? formatValue(value) : Math.round(value).toString());
      }
    });
    return () => animation.stop();
  }, [inView, target, formatValue]);

  return (
    <span ref={ref} className="stats-card__value">
      {display}
    </span>
  );
};

const ProjectOverview = () => {
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <div className="project-overview">
      <nav className="po-nav">
        <div className="po-nav__brand">
          <span className="po-nav__dot" />
          <span className="po-nav__title">Loan Wizard</span>
        </div>
        <div className="po-nav__links">
          <a href="#features">Features</a>
          <a href="#architecture">Architecture</a>
          <a href="#team">Team</a>
          <a href="#judging">Judging</a>
        </div>
        <Link to="/dashboard" className="po-nav__cta">
          View Dashboard
        </Link>
      </nav>

      <FadeInSection className="hero" delay={0}>
        <p className="hero__pill">
          <span className="hero__pill-dot" />
          TenzorX 2026 · Poonawalla Fincorp · PS3
        </p>
        <h1>Agentic AI Loan Onboarding.</h1>
        <p className="hero__subtitle">
          A live video call replaces the paper application. AI scores identity, intent, and risk in real time — then
          generates a personalised offer with a full audit trail.
        </p>
        <div className="hero__actions">
          <Link to="/dashboard" className="btn btn--primary">
            View Dashboard →
          </Link>
          <button className="btn btn--ghost">Watch Demo</button>
        </div>
        <div className="hero__scroll">
          <span className="hero__scroll-line" />
          <motion.span
            className="hero__scroll-chevron"
            animate={{ y: [0, 6, 0] }}
            transition={{ repeat: Infinity, duration: 1.4 }}
          >
            ˅
          </motion.span>
        </div>
      </FadeInSection>

      <FadeInSection className="stats-section">
        <div className="stats-grid">
          {stats.map((stat, index) => (
            <motion.article
              key={stat.label}
              className="stats-card"
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
            >
              <div className="stats-card__value-wrap">
                <AnimatedCounter target={stat.target} formatValue={stat.format} />
                {stat.unit && <span className="stats-card__unit">{stat.unit}</span>}
              </div>
              <p className="stats-card__label">{stat.label}</p>
              <p className="stats-card__caption">{stat.caption}</p>
            </motion.article>
          ))}
        </div>
      </FadeInSection>

      <FadeInSection className="features-section" id="features">
        <div className="section-label">Platform Features</div>
        <h2>Every feature a real lending system needs.</h2>
        <div className="features-grid">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <motion.article
                key={feature.title}
                className="feature-card"
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
              >
                <div className="feature-card__icon">
                  <Icon size={24} />
                </div>
                <h3>{feature.title}</h3>
                <p>{feature.description}</p>
                <a href={feature.link} className="feature-card__link">
                  Explore →
                </a>
              </motion.article>
            );
          })}
        </div>
      </FadeInSection>

      <FadeInSection className="tech-section" id="architecture">
        <div className="section-label">Tech Stack</div>
        <h2>Cloud-assisted. Event-driven. Production-grade.</h2>
        <div className="tech-grid">
          <div className="tech-list">
            {techStack.map((tech) => (
              <div key={tech.label} className="tech-list__item">
                <span>{tech.label}</span>
                <span className="tech-list__value">{tech.value}</span>
              </div>
            ))}
          </div>
          <pre className="tech-code" aria-label="Repository structure">
            {repoStructure}
          </pre>
        </div>
      </FadeInSection>

      <FadeInSection className="team-section" id="team">
        <div className="section-label">The Team</div>
        <h2>Built by VIT Bhopal University · TenzorX 2026</h2>
        <div className="team-grid">
          {teamMembers.map((member) => (
            <motion.article
              key={member.name}
              className="team-card"
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
            >
              <div className="team-card__avatar">{member.initials}</div>
              <h3>{member.name}</h3>
              <p className="team-card__role">{member.role}</p>
              <p className="team-card__detail">{member.detail}</p>
            </motion.article>
          ))}
        </div>
      </FadeInSection>

      <FadeInSection className="judging-section" id="judging">
        <div className="section-label">Judging Criteria</div>
        <h2>Built to score on every criterion.</h2>
        <div className="judging-accordion">
          {judgingCriteria.map((item, index) => {
            const isOpen = openIndex === index;
            return (
              <div key={item.title} className="accordion-item">
                <button type="button" className="accordion-trigger" onClick={() => setOpenIndex(isOpen ? null : index)}>
                  <span>{item.title}</span>
                  <span>{isOpen ? '−' : '+'}</span>
                </button>
                <motion.div
                  className="accordion-content"
                  initial={{ height: 0, opacity: 0 }}
                  animate={isOpen ? { height: 'auto', opacity: 1 } : { height: 0, opacity: 0 }}
                  transition={{ duration: 0.3 }}
                >
                  <p>{item.description}</p>
                </motion.div>
              </div>
            );
          })}
        </div>
      </FadeInSection>

      <FadeInSection className="cta-section">
        <h2>See it in action.</h2>
        <p>
          Walk through a complete loan onboarding session — from video call to offer acceptance.
        </p>
        <Link className="btn btn--primary" to="/dashboard">
          Open Dashboard →
        </Link>
      </FadeInSection>

      <footer className="po-footer">
        Loan Wizard · TenzorX 2026 · Poonawalla Fincorp · VIT Bhopal University · Built with FastAPI, React, XGBoost, and Groq
      </footer>
    </div>
  );
};

export default ProjectOverview;
